---
title: "loops_and_functions"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(here)
library(janitor)

weekdays <- c("monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday")
transects <- c("transect a", "transect b", "transect c")

out_matrix <- matrix(nrow=length(weekdays), ncol=length(transects))

for(i in seq_along(weekdays)){
  for(j in seq_along(transects))
  out_matrix[i,j] <- print(paste0(weekdays[i], "- ", transects[j]))
}
```

```{r}

force <- function(mass, acceleration){
  newtons <- mass*acceleration
  print(paste("The resulting force is", (newtons), "Newtons"))
}

force(5, 6)
```

```{r}
  fish_parms <- data.frame(sci_name = c("chanos chanos", 
                                      "sphyraena barracuda", 
                                      "caranx ignobilis"),
                         common_name = c("milkfish", 
                                         "great barracuda", 
                                         "giant trevally"),
                         a_est = c(0.0905, 0.0181, 0.0353),
                         b_est = c(2.52, 3.27, 3.05))



fish_weight <- function(fish_name, tot_length){
  fish_select <- filter(fish_parms, common_name == fish_name)
  est_weight <- fish_select$a_est*tot_length^fish_select$b_est
  print(paste("The estimated weight of your fish is", est_weight))
  
}


fish_weight("milkfish", 6)

fish_lengths <- seq(from=0, to=100, by=1)

milkfish_weights <- fish_weight("milkfish", fish_lengths) 




```

```{r}

wave_vec <- seq(from=0, to=3, by=0.2)
wave_power <- function(wave_height, period){
  power = 0.5 * wave_height^2 * period
  return(power)
}
  
wave_power(wave_vec, 8)
```






















